### ISSUE TITLE
How do I burn this?

### ISSUE THREAD

**Issue by AronRubin** [superwofy/GD32_I2C_CAN_FIRMWARE#1]
How do I burn this onto the embedded device?

**Comment by superwofy** [comment]
Hello Aron,

You need an SWD interface such as a J-link. There are SWD pads for the GD32 chip under the board.
The code is unfinished and untested however. FIFO is not yet implemented for the can buffers. Longan used LIFO which is definitely wrong.

**Comment by superwofy** [comment]
> How do I burn this onto the embedded device?

Hello Aron,

You need an SWD interface such as a J-link. There are SWD pads for the GD32 chip under the board.
The code is unfinished and untested however. FIFO is not yet implemented for the can buffers. Longan used LIFO which is definitely wrong.

**Comment by aalm** [comment]
So I got the stlink v3, and had no luck trying to flash this via keil ide with what I think should be the correct configuration.
Possibly the same issue as with tools by stm - it doesn't find stm32 target(despite having chosen GD32E103 as the target in project settings).

Tested some tools on linux too, with no luck since coreid didn't match anything expected, and simply changing it in ie. stm32f1x.cfg for openocd wasn't enough(possibly because cm4 vs. cm3 difference?).

Unsure what I should try next, so I did order ~cheapest j-link clone I found on ebay hoping it will work better with keil ide than stlink for non-stm chips, for something as simple as flashing via swd.

**Comment by aalm** [comment]
I hope this is now 'solved' for me, as it seems* like [BMP](https://black-magic.org/)(I used a bluepill as BMP) does work for this.


BMP does want .elf, and this does provide one that does get loaded to the flash:
>aalm@rpi4:~ $ arm-none-eabi-objcopy -I binary -O elf32-littlearm --change-section-address=.data=0x8000000 -B arm -S GD32_I2C_CAN_FIRMWARE.bin GD32_I2C_CAN_FIRMWARE.elf


Flashing the .elf with BMP([example](https://black-magic.org/usage/gdb-automation.html) of one-liner to do this):
>aalm@rpi4:~ $ gdb-multiarch 
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
>
> For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) target extended-remote /dev/ttyACM0
Remote debugging using /dev/ttyACM0
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x08001996 in ?? ()
(gdb) monitor swdp_scan
Target voltage: 2.84V
You are now detached from the previous target.
Available Targets:
No. Att Driver
 1      GD32F3 M4
(gdb) attach 1
A program is being debugged already.  Kill it? (y or n) y
Attaching to Remote target
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x08001994 in ?? ()
(gdb) load ~/GD32_I2C_CAN_FIRMWARE.elf 
Loading section .data, size 0x2b60 lma 0x8000000
Start address 0x00000000, load size 11104
Transfer rate: 38 KB/sec, 925 bytes/write.
(gdb) kill
Kill the program being debugged? (y or n) y
[Inferior 1 (Remote target) killed]
(gdb) q


*) haven't actually tested the firmware yet, as I didn't want to touch the rp2040 side of the board/code before sorting out CAN.

**Comment by superwofy** [comment]
If you ever need to go back to stock, I made this dump: https://github.com/superwofy/GD32_I2C_CAN_FIRMWARE/blob/main/original%20canbed%20v1.1%20gd32%20dump.bin

To use this firmware, I also adapted the rp2040 library - again, untested.
